"""Sensor definitions for DQ Platform checks."""

# Re-export core types
from dq_platform.checks.sensors._base import (
    QUOTE_CHARS as QUOTE_CHARS,
)
from dq_platform.checks.sensors._base import (
    Sensor as Sensor,
)
from dq_platform.checks.sensors._base import (
    SensorType as SensorType,
)
from dq_platform.checks.sensors._column_advanced import *  # noqa: F401, F403
from dq_platform.checks.sensors._column_advanced import (
    DISTINCT_COUNT_CHANGE_1_DAY_SENSOR,
    DISTINCT_COUNT_CHANGE_7_DAYS_SENSOR,
    DISTINCT_COUNT_CHANGE_30_DAYS_SENSOR,
    DISTINCT_COUNT_CHANGE_SENSOR,
    DISTINCT_PERCENT_CHANGE_1_DAY_SENSOR,
    DISTINCT_PERCENT_CHANGE_7_DAYS_SENSOR,
    DISTINCT_PERCENT_CHANGE_30_DAYS_SENSOR,
    DISTINCT_PERCENT_CHANGE_SENSOR,
    FOREIGN_KEY_FOUND_PERCENT_SENSOR,
    FOREIGN_KEY_NOT_FOUND_COUNT_SENSOR,
    IMPORT_CUSTOM_RESULT_ON_COLUMN_SENSOR,
    MEAN_CHANGE_1_DAY_SENSOR,
    MEAN_CHANGE_7_DAYS_SENSOR,
    MEAN_CHANGE_30_DAYS_SENSOR,
    MEAN_CHANGE_SENSOR,
    MEDIAN_CHANGE_1_DAY_SENSOR,
    MEDIAN_CHANGE_7_DAYS_SENSOR,
    MEDIAN_CHANGE_30_DAYS_SENSOR,
    MEDIAN_CHANGE_SENSOR,
    NULLS_PERCENT_CHANGE_1_DAY_SENSOR,
    NULLS_PERCENT_CHANGE_7_DAYS_SENSOR,
    NULLS_PERCENT_CHANGE_30_DAYS_SENSOR,
    NULLS_PERCENT_CHANGE_SENSOR,
    SQL_AGGREGATE_ON_COLUMN_VALUE_SENSOR,
    SQL_CONDITION_FAILED_ON_COLUMN_COUNT_SENSOR,
    SQL_CONDITION_PASSED_ON_COLUMN_PERCENT_SENSOR,
    SQL_INVALID_VALUE_ON_COLUMN_COUNT_SENSOR,
    SUM_CHANGE_1_DAY_SENSOR,
    SUM_CHANGE_7_DAYS_SENSOR,
    SUM_CHANGE_30_DAYS_SENSOR,
    SUM_CHANGE_SENSOR,
)
from dq_platform.checks.sensors._column_core import *  # noqa: F401, F403
from dq_platform.checks.sensors._column_core import (
    DISTINCT_COUNT_SENSOR,
    DISTINCT_PERCENT_SENSOR,
    DUPLICATE_COUNT_SENSOR,
    DUPLICATE_PERCENT_SENSOR,
    EMPTY_TEXT_COUNT_SENSOR,
    EMPTY_TEXT_PERCENT_SENSOR,
    INTEGER_IN_RANGE_PERCENT_SENSOR,
    MAX_VALUE_SENSOR,
    MEAN_VALUE_SENSOR,
    MEDIAN_VALUE_SENSOR,
    MIN_VALUE_SENSOR,
    NEGATIVE_VALUE_COUNT_SENSOR,
    NEGATIVE_VALUE_PERCENT_SENSOR,
    NON_NEGATIVE_VALUE_COUNT_SENSOR,
    NON_NEGATIVE_VALUE_PERCENT_SENSOR,
    NOT_NULLS_COUNT_SENSOR,
    NOT_NULLS_PERCENT_SENSOR,
    NULL_PLACEHOLDER_TEXT_COUNT_SENSOR,
    NULLS_COUNT_SENSOR,
    NULLS_PERCENT_SENSOR,
    NUMBER_ABOVE_MAX_PERCENT_SENSOR,
    NUMBER_BELOW_MIN_PERCENT_SENSOR,
    NUMBER_IN_RANGE_PERCENT_SENSOR,
    PERCENTILE_10_SENSOR,
    PERCENTILE_25_SENSOR,
    PERCENTILE_75_SENSOR,
    PERCENTILE_90_SENSOR,
    PERCENTILE_SENSOR,
    REGEX_MATCH_COUNT_SENSOR,
    REGEX_MATCH_PERCENT_SENSOR,
    REGEX_NOT_MATCH_COUNT_SENSOR,
    REGEX_NOT_MATCH_PERCENT_SENSOR,
    STDDEV_POPULATION_SENSOR,
    STDDEV_SAMPLE_SENSOR,
    SUM_VALUE_SENSOR,
    TEXT_LENGTH_ABOVE_MAX_PERCENT_SENSOR,
    TEXT_LENGTH_ABOVE_MAX_SENSOR,
    TEXT_LENGTH_BELOW_MIN_PERCENT_SENSOR,
    TEXT_LENGTH_BELOW_MIN_SENSOR,
    TEXT_LENGTH_IN_RANGE_PERCENT_SENSOR,
    TEXT_MAX_LENGTH_SENSOR,
    TEXT_MEAN_LENGTH_SENSOR,
    TEXT_MIN_LENGTH_SENSOR,
    TEXT_SURROUNDED_WHITESPACE_COUNT_SENSOR,
    TEXT_WORD_COUNT_MAX_SENSOR,
    TEXT_WORD_COUNT_MIN_SENSOR,
    VARIANCE_POPULATION_SENSOR,
    VARIANCE_SAMPLE_SENSOR,
    WHITESPACE_TEXT_COUNT_SENSOR,
    WHITESPACE_TEXT_PERCENT_SENSOR,
)
from dq_platform.checks.sensors._column_pattern import *  # noqa: F401, F403
from dq_platform.checks.sensors._column_pattern import (
    CONTAINS_EMAIL_PERCENT_SENSOR,
    CONTAINS_IP4_PERCENT_SENSOR,
    CONTAINS_IP6_PERCENT_SENSOR,
    CONTAINS_PHONE_PERCENT_SENSOR,
    CONTAINS_ZIPCODE_PERCENT_SENSOR,
    DATE_IN_RANGE_COUNT_SENSOR,
    DATE_IN_RANGE_PERCENT_SENSOR,
    DETECTED_DATATYPE_CHANGED_SENSOR,
    DETECTED_DATATYPE_SENSOR,
    EXPECTED_NUMBER_IN_USE_COUNT_SENSOR,
    EXPECTED_TEXT_IN_USE_COUNT_SENSOR,
    EXPECTED_TEXTS_TOP_N_COUNT_SENSOR,
    FALSE_COUNT_SENSOR,
    FALSE_PERCENT_SENSOR,
    FUTURE_DATE_COUNT_SENSOR,
    FUTURE_DATE_PERCENT_SENSOR,
    INVALID_EMAIL_FORMAT_COUNT_SENSOR,
    INVALID_IP4_FORMAT_COUNT_SENSOR,
    INVALID_IP6_FORMAT_COUNT_SENSOR,
    INVALID_LATITUDE_COUNT_SENSOR,
    INVALID_LONGITUDE_COUNT_SENSOR,
    INVALID_PHONE_FORMAT_COUNT_SENSOR,
    INVALID_UUID_FORMAT_COUNT_SENSOR,
    INVALID_ZIPCODE_FORMAT_COUNT_SENSOR,
    NUMBER_IN_SET_PERCENT_SENSOR,
    TEXT_IN_SET_PERCENT_SENSOR,
    TEXT_MATCH_DATE_PERCENT_SENSOR,
    TEXT_NOT_MATCHING_DATE_COUNT_SENSOR,
    TEXT_NOT_MATCHING_NAME_PERCENT_SENSOR,
    TEXT_PARSABLE_BOOLEAN_PERCENT_SENSOR,
    TEXT_PARSABLE_DATE_PERCENT_SENSOR,
    TEXT_PARSABLE_FLOAT_PERCENT_SENSOR,
    TEXT_PARSABLE_INTEGER_PERCENT_SENSOR,
    TRUE_COUNT_SENSOR,
    TRUE_PERCENT_SENSOR,
    VALID_COUNTRY_CODE_PERCENT_SENSOR,
    VALID_CURRENCY_CODE_PERCENT_SENSOR,
    VALID_LATITUDE_PERCENT_SENSOR,
    VALID_LONGITUDE_PERCENT_SENSOR,
)

# Import all sensor definitions (needed for registry population)
from dq_platform.checks.sensors._table import *  # noqa: F401, F403

# Import sensor variables explicitly for the registry
from dq_platform.checks.sensors._table import (
    AVERAGE_MATCH_PERCENT_SENSOR,
    COLUMN_COUNT_SENSOR,
    COLUMN_EXISTS_SENSOR,
    COLUMN_LIST_HASH_SENSOR,
    COLUMN_LIST_OR_ORDER_HASH_SENSOR,
    COLUMN_TYPE_CHANGED_SENSOR,
    COLUMN_TYPES_HASH_SENSOR,
    DATA_FRESHNESS_SENSOR,
    DATA_INGESTION_DELAY_SENSOR,
    DATA_STALENESS_SENSOR,
    DUPLICATE_RECORD_COUNT_SENSOR,
    DUPLICATE_RECORD_PERCENT_SENSOR,
    IMPORT_CUSTOM_RESULT_ON_TABLE_SENSOR,
    MAX_MATCH_PERCENT_SENSOR,
    MIN_MATCH_PERCENT_SENSOR,
    NOT_NULL_COUNT_MATCH_PERCENT_SENSOR,
    RELOAD_LAG_SENSOR,
    ROW_COUNT_CHANGE_1_DAY_SENSOR,
    ROW_COUNT_CHANGE_7_DAYS_SENSOR,
    ROW_COUNT_CHANGE_30_DAYS_SENSOR,
    ROW_COUNT_CHANGE_SENSOR,
    ROW_COUNT_MATCH_PERCENT_SENSOR,
    ROW_COUNT_SENSOR,
    SQL_AGGREGATE_VALUE_SENSOR,
    SQL_CONDITION_FAILED_COUNT_SENSOR,
    SQL_CONDITION_PASSED_PERCENT_SENSOR,
    SQL_INVALID_RECORD_COUNT_SENSOR,
    SUM_MATCH_PERCENT_SENSOR,
    TABLE_AVAILABILITY_SENSOR,
)

# =============================================================================
# Sensor Registry
# =============================================================================

SENSOR_REGISTRY: dict[SensorType, Sensor] = {
    # Volume
    SensorType.ROW_COUNT: ROW_COUNT_SENSOR,
    SensorType.ROW_COUNT_CHANGE_1_DAY: ROW_COUNT_CHANGE_1_DAY_SENSOR,
    SensorType.ROW_COUNT_CHANGE_7_DAYS: ROW_COUNT_CHANGE_7_DAYS_SENSOR,
    SensorType.ROW_COUNT_CHANGE_30_DAYS: ROW_COUNT_CHANGE_30_DAYS_SENSOR,
    # Schema
    SensorType.COLUMN_COUNT: COLUMN_COUNT_SENSOR,
    SensorType.COLUMN_EXISTS: COLUMN_EXISTS_SENSOR,
    # Timeliness
    SensorType.DATA_FRESHNESS: DATA_FRESHNESS_SENSOR,
    SensorType.DATA_STALENESS: DATA_STALENESS_SENSOR,
    # Nulls/Completeness
    SensorType.NULLS_COUNT: NULLS_COUNT_SENSOR,
    SensorType.NULLS_PERCENT: NULLS_PERCENT_SENSOR,
    SensorType.NOT_NULLS_COUNT: NOT_NULLS_COUNT_SENSOR,
    SensorType.NOT_NULLS_PERCENT: NOT_NULLS_PERCENT_SENSOR,
    # Uniqueness
    SensorType.DISTINCT_COUNT: DISTINCT_COUNT_SENSOR,
    SensorType.DISTINCT_PERCENT: DISTINCT_PERCENT_SENSOR,
    SensorType.DUPLICATE_COUNT: DUPLICATE_COUNT_SENSOR,
    SensorType.DUPLICATE_PERCENT: DUPLICATE_PERCENT_SENSOR,
    # Numeric/Statistical
    SensorType.MIN_VALUE: MIN_VALUE_SENSOR,
    SensorType.MAX_VALUE: MAX_VALUE_SENSOR,
    SensorType.SUM_VALUE: SUM_VALUE_SENSOR,
    SensorType.MEAN_VALUE: MEAN_VALUE_SENSOR,
    SensorType.MEDIAN_VALUE: MEDIAN_VALUE_SENSOR,
    SensorType.STDDEV_SAMPLE: STDDEV_SAMPLE_SENSOR,
    SensorType.STDDEV_POPULATION: STDDEV_POPULATION_SENSOR,
    SensorType.VARIANCE_SAMPLE: VARIANCE_SAMPLE_SENSOR,
    SensorType.VARIANCE_POPULATION: VARIANCE_POPULATION_SENSOR,
    SensorType.PERCENTILE: PERCENTILE_SENSOR,
    # Text/Pattern
    SensorType.TEXT_MIN_LENGTH: TEXT_MIN_LENGTH_SENSOR,
    SensorType.TEXT_MAX_LENGTH: TEXT_MAX_LENGTH_SENSOR,
    SensorType.TEXT_MEAN_LENGTH: TEXT_MEAN_LENGTH_SENSOR,
    SensorType.TEXT_LENGTH_BELOW_MIN: TEXT_LENGTH_BELOW_MIN_SENSOR,
    SensorType.TEXT_LENGTH_ABOVE_MAX: TEXT_LENGTH_ABOVE_MAX_SENSOR,
    SensorType.TEXT_LENGTH_IN_RANGE_PERCENT: TEXT_LENGTH_IN_RANGE_PERCENT_SENSOR,
    SensorType.EMPTY_TEXT_COUNT: EMPTY_TEXT_COUNT_SENSOR,
    SensorType.WHITESPACE_TEXT_COUNT: WHITESPACE_TEXT_COUNT_SENSOR,
    SensorType.REGEX_MATCH_COUNT: REGEX_MATCH_COUNT_SENSOR,
    SensorType.REGEX_NOT_MATCH_COUNT: REGEX_NOT_MATCH_COUNT_SENSOR,
    # Geographic
    SensorType.INVALID_LATITUDE_COUNT: INVALID_LATITUDE_COUNT_SENSOR,
    SensorType.INVALID_LONGITUDE_COUNT: INVALID_LONGITUDE_COUNT_SENSOR,
    # Boolean
    SensorType.TRUE_COUNT: TRUE_COUNT_SENSOR,
    SensorType.TRUE_PERCENT: TRUE_PERCENT_SENSOR,
    SensorType.FALSE_COUNT: FALSE_COUNT_SENSOR,
    SensorType.FALSE_PERCENT: FALSE_PERCENT_SENSOR,
    # DateTime
    SensorType.FUTURE_DATE_COUNT: FUTURE_DATE_COUNT_SENSOR,
    SensorType.FUTURE_DATE_PERCENT: FUTURE_DATE_PERCENT_SENSOR,
    SensorType.DATE_IN_RANGE_COUNT: DATE_IN_RANGE_COUNT_SENSOR,
    SensorType.DATE_IN_RANGE_PERCENT: DATE_IN_RANGE_PERCENT_SENSOR,
    # Pattern/Format
    SensorType.INVALID_EMAIL_FORMAT_COUNT: INVALID_EMAIL_FORMAT_COUNT_SENSOR,
    SensorType.INVALID_UUID_FORMAT_COUNT: INVALID_UUID_FORMAT_COUNT_SENSOR,
    SensorType.INVALID_IP4_FORMAT_COUNT: INVALID_IP4_FORMAT_COUNT_SENSOR,
    SensorType.INVALID_IP6_FORMAT_COUNT: INVALID_IP6_FORMAT_COUNT_SENSOR,
    SensorType.INVALID_PHONE_FORMAT_COUNT: INVALID_PHONE_FORMAT_COUNT_SENSOR,
    SensorType.INVALID_ZIPCODE_FORMAT_COUNT: INVALID_ZIPCODE_FORMAT_COUNT_SENSOR,
    # Referential Integrity
    SensorType.FOREIGN_KEY_NOT_FOUND_COUNT: FOREIGN_KEY_NOT_FOUND_COUNT_SENSOR,
    SensorType.FOREIGN_KEY_FOUND_PERCENT: FOREIGN_KEY_FOUND_PERCENT_SENSOR,
    # Table-level Duplicates
    SensorType.DUPLICATE_RECORD_COUNT: DUPLICATE_RECORD_COUNT_SENSOR,
    SensorType.DUPLICATE_RECORD_PERCENT: DUPLICATE_RECORD_PERCENT_SENSOR,
    # Phase 1: Whitespace & Text
    SensorType.EMPTY_TEXT_PERCENT: EMPTY_TEXT_PERCENT_SENSOR,
    SensorType.WHITESPACE_TEXT_PERCENT: WHITESPACE_TEXT_PERCENT_SENSOR,
    SensorType.NULL_PLACEHOLDER_TEXT_COUNT: NULL_PLACEHOLDER_TEXT_COUNT_SENSOR,
    SensorType.TEXT_SURROUNDED_WHITESPACE_COUNT: TEXT_SURROUNDED_WHITESPACE_COUNT_SENSOR,
    SensorType.REGEX_NOT_MATCH_PERCENT: REGEX_NOT_MATCH_PERCENT_SENSOR,
    SensorType.REGEX_MATCH_PERCENT: REGEX_MATCH_PERCENT_SENSOR,
    SensorType.TEXT_WORD_COUNT_MIN: TEXT_WORD_COUNT_MIN_SENSOR,
    SensorType.TEXT_WORD_COUNT_MAX: TEXT_WORD_COUNT_MAX_SENSOR,
    # Phase 2: Geographic
    SensorType.VALID_LATITUDE_PERCENT: VALID_LATITUDE_PERCENT_SENSOR,
    SensorType.VALID_LONGITUDE_PERCENT: VALID_LONGITUDE_PERCENT_SENSOR,
    # Phase 2: Numeric
    SensorType.NUMBER_BELOW_MIN_PERCENT: NUMBER_BELOW_MIN_PERCENT_SENSOR,
    SensorType.NUMBER_ABOVE_MAX_PERCENT: NUMBER_ABOVE_MAX_PERCENT_SENSOR,
    SensorType.NEGATIVE_VALUE_COUNT: NEGATIVE_VALUE_COUNT_SENSOR,
    SensorType.NEGATIVE_VALUE_PERCENT: NEGATIVE_VALUE_PERCENT_SENSOR,
    SensorType.NON_NEGATIVE_VALUE_COUNT: NON_NEGATIVE_VALUE_COUNT_SENSOR,
    SensorType.NON_NEGATIVE_VALUE_PERCENT: NON_NEGATIVE_VALUE_PERCENT_SENSOR,
    SensorType.INTEGER_IN_RANGE_PERCENT: INTEGER_IN_RANGE_PERCENT_SENSOR,
    SensorType.NUMBER_IN_RANGE_PERCENT: NUMBER_IN_RANGE_PERCENT_SENSOR,
    # Phase 3: Percentile
    SensorType.PERCENTILE_10: PERCENTILE_10_SENSOR,
    SensorType.PERCENTILE_25: PERCENTILE_25_SENSOR,
    SensorType.PERCENTILE_75: PERCENTILE_75_SENSOR,
    SensorType.PERCENTILE_90: PERCENTILE_90_SENSOR,
    # Phase 4: Accepted Values
    SensorType.TEXT_IN_SET_PERCENT: TEXT_IN_SET_PERCENT_SENSOR,
    SensorType.NUMBER_IN_SET_PERCENT: NUMBER_IN_SET_PERCENT_SENSOR,
    SensorType.EXPECTED_TEXT_IN_USE_COUNT: EXPECTED_TEXT_IN_USE_COUNT_SENSOR,
    SensorType.EXPECTED_NUMBER_IN_USE_COUNT: EXPECTED_NUMBER_IN_USE_COUNT_SENSOR,
    SensorType.EXPECTED_TEXTS_TOP_N_COUNT: EXPECTED_TEXTS_TOP_N_COUNT_SENSOR,
    SensorType.VALID_COUNTRY_CODE_PERCENT: VALID_COUNTRY_CODE_PERCENT_SENSOR,
    SensorType.VALID_CURRENCY_CODE_PERCENT: VALID_CURRENCY_CODE_PERCENT_SENSOR,
    # Phase 5: Date Pattern & Data Type
    SensorType.TEXT_NOT_MATCHING_DATE_COUNT: TEXT_NOT_MATCHING_DATE_COUNT_SENSOR,
    SensorType.TEXT_MATCH_DATE_PERCENT: TEXT_MATCH_DATE_PERCENT_SENSOR,
    SensorType.TEXT_NOT_MATCHING_NAME_PERCENT: TEXT_NOT_MATCHING_NAME_PERCENT_SENSOR,
    SensorType.TEXT_PARSABLE_BOOLEAN_PERCENT: TEXT_PARSABLE_BOOLEAN_PERCENT_SENSOR,
    SensorType.TEXT_PARSABLE_INTEGER_PERCENT: TEXT_PARSABLE_INTEGER_PERCENT_SENSOR,
    SensorType.TEXT_PARSABLE_FLOAT_PERCENT: TEXT_PARSABLE_FLOAT_PERCENT_SENSOR,
    SensorType.TEXT_PARSABLE_DATE_PERCENT: TEXT_PARSABLE_DATE_PERCENT_SENSOR,
    SensorType.DETECTED_DATATYPE: DETECTED_DATATYPE_SENSOR,
    SensorType.DETECTED_DATATYPE_CHANGED: DETECTED_DATATYPE_CHANGED_SENSOR,
    # Phase 6: PII Detection
    SensorType.CONTAINS_PHONE_PERCENT: CONTAINS_PHONE_PERCENT_SENSOR,
    SensorType.CONTAINS_EMAIL_PERCENT: CONTAINS_EMAIL_PERCENT_SENSOR,
    SensorType.CONTAINS_ZIPCODE_PERCENT: CONTAINS_ZIPCODE_PERCENT_SENSOR,
    SensorType.CONTAINS_IP4_PERCENT: CONTAINS_IP4_PERCENT_SENSOR,
    SensorType.CONTAINS_IP6_PERCENT: CONTAINS_IP6_PERCENT_SENSOR,
    # Phase 7: Change Detection
    SensorType.NULLS_PERCENT_CHANGE_1_DAY: NULLS_PERCENT_CHANGE_1_DAY_SENSOR,
    SensorType.NULLS_PERCENT_CHANGE_7_DAYS: NULLS_PERCENT_CHANGE_7_DAYS_SENSOR,
    SensorType.NULLS_PERCENT_CHANGE_30_DAYS: NULLS_PERCENT_CHANGE_30_DAYS_SENSOR,
    SensorType.DISTINCT_COUNT_CHANGE_1_DAY: DISTINCT_COUNT_CHANGE_1_DAY_SENSOR,
    SensorType.DISTINCT_COUNT_CHANGE_7_DAYS: DISTINCT_COUNT_CHANGE_7_DAYS_SENSOR,
    SensorType.DISTINCT_COUNT_CHANGE_30_DAYS: DISTINCT_COUNT_CHANGE_30_DAYS_SENSOR,
    SensorType.DISTINCT_PERCENT_CHANGE_1_DAY: DISTINCT_PERCENT_CHANGE_1_DAY_SENSOR,
    SensorType.DISTINCT_PERCENT_CHANGE_7_DAYS: DISTINCT_PERCENT_CHANGE_7_DAYS_SENSOR,
    SensorType.DISTINCT_PERCENT_CHANGE_30_DAYS: DISTINCT_PERCENT_CHANGE_30_DAYS_SENSOR,
    SensorType.MEAN_CHANGE_1_DAY: MEAN_CHANGE_1_DAY_SENSOR,
    SensorType.MEAN_CHANGE_7_DAYS: MEAN_CHANGE_7_DAYS_SENSOR,
    SensorType.MEAN_CHANGE_30_DAYS: MEAN_CHANGE_30_DAYS_SENSOR,
    SensorType.MEDIAN_CHANGE_1_DAY: MEDIAN_CHANGE_1_DAY_SENSOR,
    SensorType.MEDIAN_CHANGE_7_DAYS: MEDIAN_CHANGE_7_DAYS_SENSOR,
    SensorType.MEDIAN_CHANGE_30_DAYS: MEDIAN_CHANGE_30_DAYS_SENSOR,
    SensorType.SUM_CHANGE_1_DAY: SUM_CHANGE_1_DAY_SENSOR,
    SensorType.SUM_CHANGE_7_DAYS: SUM_CHANGE_7_DAYS_SENSOR,
    SensorType.SUM_CHANGE_30_DAYS: SUM_CHANGE_30_DAYS_SENSOR,
    # Phase 8: Cross-Table
    SensorType.ROW_COUNT_MATCH_PERCENT: ROW_COUNT_MATCH_PERCENT_SENSOR,
    SensorType.SUM_MATCH_PERCENT: SUM_MATCH_PERCENT_SENSOR,
    SensorType.MIN_MATCH_PERCENT: MIN_MATCH_PERCENT_SENSOR,
    SensorType.MAX_MATCH_PERCENT: MAX_MATCH_PERCENT_SENSOR,
    SensorType.AVERAGE_MATCH_PERCENT: AVERAGE_MATCH_PERCENT_SENSOR,
    SensorType.NOT_NULL_COUNT_MATCH_PERCENT: NOT_NULL_COUNT_MATCH_PERCENT_SENSOR,
    # Phase 9: Table-Level Misc
    SensorType.TABLE_AVAILABILITY: TABLE_AVAILABILITY_SENSOR,
    SensorType.DATA_INGESTION_DELAY: DATA_INGESTION_DELAY_SENSOR,
    SensorType.RELOAD_LAG: RELOAD_LAG_SENSOR,
    SensorType.SQL_CONDITION_PASSED_PERCENT: SQL_CONDITION_PASSED_PERCENT_SENSOR,
    SensorType.COLUMN_TYPE_CHANGED: COLUMN_TYPE_CHANGED_SENSOR,
    # Custom SQL
    SensorType.SQL_CONDITION_FAILED_COUNT: SQL_CONDITION_FAILED_COUNT_SENSOR,
    SensorType.SQL_AGGREGATE_VALUE: SQL_AGGREGATE_VALUE_SENSOR,
    # Phase 10: Text Length Percent
    SensorType.TEXT_LENGTH_BELOW_MIN_PERCENT: TEXT_LENGTH_BELOW_MIN_PERCENT_SENSOR,
    SensorType.TEXT_LENGTH_ABOVE_MAX_PERCENT: TEXT_LENGTH_ABOVE_MAX_PERCENT_SENSOR,
    # Phase 10: Column-Level Custom SQL
    SensorType.SQL_CONDITION_FAILED_ON_COLUMN_COUNT: SQL_CONDITION_FAILED_ON_COLUMN_COUNT_SENSOR,
    SensorType.SQL_CONDITION_PASSED_ON_COLUMN_PERCENT: SQL_CONDITION_PASSED_ON_COLUMN_PERCENT_SENSOR,
    SensorType.SQL_AGGREGATE_ON_COLUMN_VALUE: SQL_AGGREGATE_ON_COLUMN_VALUE_SENSOR,
    SensorType.SQL_INVALID_VALUE_ON_COLUMN_COUNT: SQL_INVALID_VALUE_ON_COLUMN_COUNT_SENSOR,
    SensorType.IMPORT_CUSTOM_RESULT_ON_COLUMN: IMPORT_CUSTOM_RESULT_ON_COLUMN_SENSOR,
    # Phase 10: Table-Level Custom SQL
    SensorType.SQL_INVALID_RECORD_COUNT: SQL_INVALID_RECORD_COUNT_SENSOR,
    # Phase 10: Schema Detection
    SensorType.COLUMN_LIST_HASH: COLUMN_LIST_HASH_SENSOR,
    SensorType.COLUMN_LIST_OR_ORDER_HASH: COLUMN_LIST_OR_ORDER_HASH_SENSOR,
    SensorType.COLUMN_TYPES_HASH: COLUMN_TYPES_HASH_SENSOR,
    # Phase 11: Import and Generic Change Detection
    SensorType.IMPORT_CUSTOM_RESULT_ON_TABLE: IMPORT_CUSTOM_RESULT_ON_TABLE_SENSOR,
    SensorType.ROW_COUNT_CHANGE: ROW_COUNT_CHANGE_SENSOR,
    SensorType.NULLS_PERCENT_CHANGE: NULLS_PERCENT_CHANGE_SENSOR,
    SensorType.DISTINCT_COUNT_CHANGE: DISTINCT_COUNT_CHANGE_SENSOR,
    SensorType.DISTINCT_PERCENT_CHANGE: DISTINCT_PERCENT_CHANGE_SENSOR,
    SensorType.MEAN_CHANGE: MEAN_CHANGE_SENSOR,
    SensorType.MEDIAN_CHANGE: MEDIAN_CHANGE_SENSOR,
    SensorType.SUM_CHANGE: SUM_CHANGE_SENSOR,
}


def get_sensor(sensor_type: SensorType) -> Sensor:
    """Get a sensor by type.

    Args:
        sensor_type: The type of sensor to retrieve.

    Returns:
        The sensor definition.

    Raises:
        ValueError: If sensor type is not registered.
    """
    if sensor_type not in SENSOR_REGISTRY:
        raise ValueError(f"Unknown sensor type: {sensor_type}")
    return SENSOR_REGISTRY[sensor_type]


def list_sensors() -> list[Sensor]:
    """List all registered sensors.

    Returns:
        List of all sensors.
    """
    return list(SENSOR_REGISTRY.values())


def get_column_level_sensors() -> list[Sensor]:
    """Get all column-level sensors.

    Returns:
        List of column-level sensors.
    """
    return [s for s in SENSOR_REGISTRY.values() if s.is_column_level]


def get_table_level_sensors() -> list[Sensor]:
    """Get all table-level sensors.

    Returns:
        List of table-level sensors.
    """
    return [s for s in SENSOR_REGISTRY.values() if not s.is_column_level]
