"""DQOps check definitions for DQ Platform."""

# Re-export core types
from dq_platform.checks.dqops_checks._base import (
    DQOpsCheck as DQOpsCheck,
)
from dq_platform.checks.dqops_checks._base import (
    DQOpsCheckType as DQOpsCheckType,
)
from dq_platform.checks.dqops_checks._column_advanced import *  # noqa: F401, F403
from dq_platform.checks.dqops_checks._column_advanced import (
    COLUMN_COUNT_MATCH_CHECK,
    COLUMN_EXISTS_CHECK,
    COLUMN_TYPE_CHANGED_CHECK,
    DATA_FRESHNESS_ANOMALY_CHECK,
    DATA_FRESHNESS_CHECK,
    DATA_INGESTION_DELAY_CHECK,
    DISTINCT_COUNT_ANOMALY_CHECK,
    DISTINCT_COUNT_CHANGE_1_DAY_CHECK,
    DISTINCT_COUNT_CHANGE_7_DAYS_CHECK,
    DISTINCT_COUNT_CHANGE_30_DAYS_CHECK,
    DISTINCT_COUNT_CHANGE_CHECK,
    DISTINCT_COUNT_MATCH_CHECK,
    DISTINCT_PERCENT_ANOMALY_CHECK,
    DISTINCT_PERCENT_CHANGE_1_DAY_CHECK,
    DISTINCT_PERCENT_CHANGE_7_DAYS_CHECK,
    DISTINCT_PERCENT_CHANGE_30_DAYS_CHECK,
    DISTINCT_PERCENT_CHANGE_CHECK,
    FOREIGN_KEY_FOUND_PERCENT_CHECK,
    FOREIGN_KEY_NOT_FOUND_CHECK,
    IMPORT_CUSTOM_RESULT_ON_COLUMN_CHECK,
    MAX_ANOMALY_CHECK,
    MAX_MATCH_CHECK,
    MEAN_ANOMALY_CHECK,
    MEAN_CHANGE_1_DAY_CHECK,
    MEAN_CHANGE_7_DAYS_CHECK,
    MEAN_CHANGE_30_DAYS_CHECK,
    MEAN_CHANGE_CHECK,
    MEAN_MATCH_CHECK,
    MEDIAN_ANOMALY_CHECK,
    MEDIAN_CHANGE_1_DAY_CHECK,
    MEDIAN_CHANGE_7_DAYS_CHECK,
    MEDIAN_CHANGE_30_DAYS_CHECK,
    MEDIAN_CHANGE_CHECK,
    MIN_ANOMALY_CHECK,
    MIN_MATCH_CHECK,
    NOT_NULL_COUNT_MATCH_CHECK,
    NULL_COUNT_MATCH_CHECK,
    NULLS_PERCENT_ANOMALY_CHECK,
    NULLS_PERCENT_CHANGE_1_DAY_CHECK,
    NULLS_PERCENT_CHANGE_7_DAYS_CHECK,
    NULLS_PERCENT_CHANGE_30_DAYS_CHECK,
    NULLS_PERCENT_CHANGE_CHECK,
    ROW_COUNT_ANOMALY_CHECK,
    ROW_COUNT_CHANGE_CHECK,
    ROW_COUNT_MATCH_CHECK,
    SQL_AGGREGATE_EXPRESSION_ON_COLUMN_CHECK,
    SQL_CONDITION_FAILED_ON_COLUMN_CHECK,
    SQL_CONDITION_PASSED_PERCENT_ON_COLUMN_CHECK,
    SQL_INVALID_VALUE_COUNT_ON_COLUMN_CHECK,
    SUM_ANOMALY_CHECK,
    SUM_CHANGE_1_DAY_CHECK,
    SUM_CHANGE_7_DAYS_CHECK,
    SUM_CHANGE_30_DAYS_CHECK,
    SUM_CHANGE_CHECK,
    SUM_MATCH_CHECK,
    TOTAL_AVERAGE_MATCH_PERCENT_CHECK,
    TOTAL_MAX_MATCH_PERCENT_CHECK,
    TOTAL_MIN_MATCH_PERCENT_CHECK,
    TOTAL_NOT_NULL_COUNT_MATCH_PERCENT_CHECK,
    TOTAL_ROW_COUNT_MATCH_PERCENT_CHECK,
    TOTAL_SUM_MATCH_PERCENT_CHECK,
)
from dq_platform.checks.dqops_checks._column_core import *  # noqa: F401, F403
from dq_platform.checks.dqops_checks._column_core import (
    DISTINCT_COUNT_CHECK,
    DISTINCT_PERCENT_CHECK,
    DUPLICATE_COUNT_CHECK,
    DUPLICATE_PERCENT_CHECK,
    EMPTY_COLUMN_FOUND_CHECK,
    EMPTY_TEXT_FOUND_CHECK,
    EMPTY_TEXT_PERCENT_CHECK,
    INTEGER_IN_RANGE_PERCENT_CHECK,
    MAX_IN_RANGE_CHECK,
    MAX_WORD_COUNT_CHECK,
    MEAN_IN_RANGE_CHECK,
    MEDIAN_IN_RANGE_CHECK,
    MIN_IN_RANGE_CHECK,
    MIN_WORD_COUNT_CHECK,
    NEGATIVE_VALUES_CHECK,
    NEGATIVE_VALUES_PERCENT_CHECK,
    NON_NEGATIVE_VALUES_CHECK,
    NON_NEGATIVE_VALUES_PERCENT_CHECK,
    NOT_NULLS_COUNT_CHECK,
    NOT_NULLS_PERCENT_CHECK,
    NULL_PLACEHOLDER_TEXT_FOUND_CHECK,
    NULL_PLACEHOLDER_TEXT_PERCENT_CHECK,
    NULLS_COUNT_CHECK,
    NULLS_PERCENT_CHECK,
    NUMBER_ABOVE_MAX_VALUE_CHECK,
    NUMBER_ABOVE_MAX_VALUE_PERCENT_CHECK,
    NUMBER_BELOW_MIN_VALUE_CHECK,
    NUMBER_BELOW_MIN_VALUE_PERCENT_CHECK,
    NUMBER_IN_RANGE_PERCENT_CHECK,
    PERCENTILE_10_IN_RANGE_CHECK,
    PERCENTILE_25_IN_RANGE_CHECK,
    PERCENTILE_75_IN_RANGE_CHECK,
    PERCENTILE_90_IN_RANGE_CHECK,
    PERCENTILE_IN_RANGE_CHECK,
    POPULATION_STDDEV_IN_RANGE_CHECK,
    POPULATION_VARIANCE_IN_RANGE_CHECK,
    SAMPLE_STDDEV_IN_RANGE_CHECK,
    SAMPLE_VARIANCE_IN_RANGE_CHECK,
    SUM_IN_RANGE_CHECK,
    TEXT_LENGTH_ABOVE_MAX_LENGTH_CHECK,
    TEXT_LENGTH_ABOVE_MAX_LENGTH_PERCENT_CHECK,
    TEXT_LENGTH_BELOW_MIN_LENGTH_CHECK,
    TEXT_LENGTH_BELOW_MIN_LENGTH_PERCENT_CHECK,
    TEXT_LENGTH_IN_RANGE_PERCENT_CHECK,
    TEXT_MATCHING_REGEX_PERCENT_CHECK,
    TEXT_MAX_LENGTH_CHECK,
    TEXT_MEAN_LENGTH_CHECK,
    TEXT_MIN_LENGTH_CHECK,
    TEXT_NOT_MATCHING_REGEX_FOUND_CHECK,
    TEXT_SURROUNDED_BY_WHITESPACE_FOUND_CHECK,
    TEXT_SURROUNDED_BY_WHITESPACE_PERCENT_CHECK,
    TEXTS_NOT_MATCHING_REGEX_PERCENT_CHECK,
    VALID_LATITUDE_PERCENT_CHECK,
    VALID_LONGITUDE_PERCENT_CHECK,
    WHITESPACE_TEXT_FOUND_CHECK,
    WHITESPACE_TEXT_PERCENT_CHECK,
)
from dq_platform.checks.dqops_checks._column_pattern import *  # noqa: F401, F403
from dq_platform.checks.dqops_checks._column_pattern import (
    CONTAINS_EMAIL_PERCENT_CHECK,
    CONTAINS_IP4_PERCENT_CHECK,
    CONTAINS_IP6_PERCENT_CHECK,
    CONTAINS_USA_PHONE_PERCENT_CHECK,
    CONTAINS_USA_ZIPCODE_PERCENT_CHECK,
    DATE_IN_RANGE_PERCENT_CHECK,
    DATE_VALUES_IN_FUTURE_PERCENT_CHECK,
    DETECTED_DATATYPE_IN_TEXT_CHANGED_CHECK,
    DETECTED_DATATYPE_IN_TEXT_CHECK,
    EXPECTED_NUMBERS_IN_USE_COUNT_CHECK,
    EXPECTED_TEXT_VALUES_IN_USE_COUNT_CHECK,
    EXPECTED_TEXTS_IN_TOP_VALUES_COUNT_CHECK,
    FALSE_PERCENT_CHECK,
    INVALID_EMAIL_FORMAT_FOUND_CHECK,
    INVALID_EMAIL_FORMAT_PERCENT_CHECK,
    INVALID_IP4_FORMAT_FOUND_CHECK,
    INVALID_IP4_FORMAT_PERCENT_CHECK,
    INVALID_IP6_FORMAT_FOUND_CHECK,
    INVALID_IP6_FORMAT_PERCENT_CHECK,
    INVALID_LATITUDE_CHECK,
    INVALID_LONGITUDE_CHECK,
    INVALID_USA_PHONE_FORMAT_FOUND_CHECK,
    INVALID_USA_PHONE_FORMAT_PERCENT_CHECK,
    INVALID_USA_ZIPCODE_FORMAT_FOUND_CHECK,
    INVALID_USA_ZIPCODE_FORMAT_PERCENT_CHECK,
    INVALID_UUID_FORMAT_FOUND_CHECK,
    INVALID_UUID_FORMAT_PERCENT_CHECK,
    NUMBER_FOUND_IN_SET_PERCENT_CHECK,
    TEXT_FOUND_IN_SET_PERCENT_CHECK,
    TEXT_MATCH_DATE_FORMAT_PERCENT_CHECK,
    TEXT_NOT_MATCHING_DATE_PATTERN_FOUND_CHECK,
    TEXT_NOT_MATCHING_DATE_PATTERN_PERCENT_CHECK,
    TEXT_NOT_MATCHING_NAME_PATTERN_PERCENT_CHECK,
    TEXT_PARSABLE_TO_BOOLEAN_PERCENT_CHECK,
    TEXT_PARSABLE_TO_DATE_PERCENT_CHECK,
    TEXT_PARSABLE_TO_FLOAT_PERCENT_CHECK,
    TEXT_PARSABLE_TO_INTEGER_PERCENT_CHECK,
    TEXT_VALID_COUNTRY_CODE_PERCENT_CHECK,
    TEXT_VALID_CURRENCY_CODE_PERCENT_CHECK,
    TRUE_PERCENT_CHECK,
)

# Import all check definitions (needed for registry)
from dq_platform.checks.dqops_checks._table import *  # noqa: F401, F403

# Import specific check variables by name for the registry
from dq_platform.checks.dqops_checks._table import (
    COLUMN_COUNT_CHANGED_CHECK,
    COLUMN_COUNT_CHECK,
    COLUMN_LIST_CHANGED_CHECK,
    COLUMN_LIST_OR_ORDER_CHANGED_CHECK,
    COLUMN_TYPES_CHANGED_CHECK,
    DATA_STALENESS_CHECK,
    DUPLICATE_RECORD_COUNT_CHECK,
    DUPLICATE_RECORD_PERCENT_CHECK,
    IMPORT_CUSTOM_RESULT_ON_TABLE_CHECK,
    RELOAD_LAG_CHECK,
    ROW_COUNT_CHANGE_1_DAY_CHECK,
    ROW_COUNT_CHANGE_7_DAYS_CHECK,
    ROW_COUNT_CHANGE_30_DAYS_CHECK,
    ROW_COUNT_CHECK,
    SQL_AGGREGATE_EXPRESSION_ON_TABLE_CHECK,
    SQL_CONDITION_FAILED_ON_TABLE_CHECK,
    SQL_CONDITION_PASSED_PERCENT_ON_TABLE_CHECK,
    SQL_INVALID_RECORD_COUNT_ON_TABLE_CHECK,
    TABLE_AVAILABILITY_CHECK,
)

# =============================================================================
# Check Registry
# =============================================================================

CHECK_REGISTRY: dict[DQOpsCheckType, DQOpsCheck] = {
    # Volume
    DQOpsCheckType.ROW_COUNT: ROW_COUNT_CHECK,
    DQOpsCheckType.ROW_COUNT_CHANGE_1_DAY: ROW_COUNT_CHANGE_1_DAY_CHECK,
    DQOpsCheckType.ROW_COUNT_CHANGE_7_DAYS: ROW_COUNT_CHANGE_7_DAYS_CHECK,
    DQOpsCheckType.ROW_COUNT_CHANGE_30_DAYS: ROW_COUNT_CHANGE_30_DAYS_CHECK,
    # Schema
    DQOpsCheckType.COLUMN_COUNT: COLUMN_COUNT_CHECK,
    DQOpsCheckType.COLUMN_EXISTS: COLUMN_EXISTS_CHECK,
    DQOpsCheckType.COLUMN_COUNT_CHANGED: COLUMN_COUNT_CHANGED_CHECK,
    # Timeliness
    DQOpsCheckType.DATA_FRESHNESS: DATA_FRESHNESS_CHECK,
    DQOpsCheckType.DATA_STALENESS: DATA_STALENESS_CHECK,
    # Nulls
    DQOpsCheckType.NULLS_COUNT: NULLS_COUNT_CHECK,
    DQOpsCheckType.NULLS_PERCENT: NULLS_PERCENT_CHECK,
    DQOpsCheckType.NOT_NULLS_COUNT: NOT_NULLS_COUNT_CHECK,
    DQOpsCheckType.NOT_NULLS_PERCENT: NOT_NULLS_PERCENT_CHECK,
    DQOpsCheckType.EMPTY_COLUMN_FOUND: EMPTY_COLUMN_FOUND_CHECK,
    # Uniqueness
    DQOpsCheckType.DISTINCT_COUNT: DISTINCT_COUNT_CHECK,
    DQOpsCheckType.DISTINCT_PERCENT: DISTINCT_PERCENT_CHECK,
    DQOpsCheckType.DUPLICATE_COUNT: DUPLICATE_COUNT_CHECK,
    DQOpsCheckType.DUPLICATE_PERCENT: DUPLICATE_PERCENT_CHECK,
    # Numeric
    DQOpsCheckType.MIN_IN_RANGE: MIN_IN_RANGE_CHECK,
    DQOpsCheckType.MAX_IN_RANGE: MAX_IN_RANGE_CHECK,
    DQOpsCheckType.SUM_IN_RANGE: SUM_IN_RANGE_CHECK,
    DQOpsCheckType.MEAN_IN_RANGE: MEAN_IN_RANGE_CHECK,
    DQOpsCheckType.MEDIAN_IN_RANGE: MEDIAN_IN_RANGE_CHECK,
    # Text
    DQOpsCheckType.TEXT_MIN_LENGTH: TEXT_MIN_LENGTH_CHECK,
    DQOpsCheckType.TEXT_MAX_LENGTH: TEXT_MAX_LENGTH_CHECK,
    DQOpsCheckType.TEXT_MEAN_LENGTH: TEXT_MEAN_LENGTH_CHECK,
    DQOpsCheckType.TEXT_LENGTH_BELOW_MIN_LENGTH: TEXT_LENGTH_BELOW_MIN_LENGTH_CHECK,
    DQOpsCheckType.TEXT_LENGTH_ABOVE_MAX_LENGTH: TEXT_LENGTH_ABOVE_MAX_LENGTH_CHECK,
    DQOpsCheckType.TEXT_LENGTH_IN_RANGE_PERCENT: TEXT_LENGTH_IN_RANGE_PERCENT_CHECK,
    DQOpsCheckType.EMPTY_TEXT_FOUND: EMPTY_TEXT_FOUND_CHECK,
    DQOpsCheckType.WHITESPACE_TEXT_FOUND: WHITESPACE_TEXT_FOUND_CHECK,
    DQOpsCheckType.TEXT_NOT_MATCHING_REGEX_FOUND: TEXT_NOT_MATCHING_REGEX_FOUND_CHECK,
    # Geographic
    DQOpsCheckType.INVALID_LATITUDE: INVALID_LATITUDE_CHECK,
    DQOpsCheckType.INVALID_LONGITUDE: INVALID_LONGITUDE_CHECK,
    # Boolean
    DQOpsCheckType.TRUE_PERCENT: TRUE_PERCENT_CHECK,
    DQOpsCheckType.FALSE_PERCENT: FALSE_PERCENT_CHECK,
    # DateTime
    DQOpsCheckType.DATE_VALUES_IN_FUTURE_PERCENT: DATE_VALUES_IN_FUTURE_PERCENT_CHECK,
    DQOpsCheckType.DATE_IN_RANGE_PERCENT: DATE_IN_RANGE_PERCENT_CHECK,
    # Pattern/Format
    DQOpsCheckType.INVALID_EMAIL_FORMAT_FOUND: INVALID_EMAIL_FORMAT_FOUND_CHECK,
    DQOpsCheckType.INVALID_EMAIL_FORMAT_PERCENT: INVALID_EMAIL_FORMAT_PERCENT_CHECK,
    DQOpsCheckType.INVALID_UUID_FORMAT_FOUND: INVALID_UUID_FORMAT_FOUND_CHECK,
    DQOpsCheckType.INVALID_UUID_FORMAT_PERCENT: INVALID_UUID_FORMAT_PERCENT_CHECK,
    DQOpsCheckType.INVALID_IP4_FORMAT_FOUND: INVALID_IP4_FORMAT_FOUND_CHECK,
    DQOpsCheckType.INVALID_IP4_FORMAT_PERCENT: INVALID_IP4_FORMAT_PERCENT_CHECK,
    DQOpsCheckType.INVALID_IP6_FORMAT_FOUND: INVALID_IP6_FORMAT_FOUND_CHECK,
    DQOpsCheckType.INVALID_IP6_FORMAT_PERCENT: INVALID_IP6_FORMAT_PERCENT_CHECK,
    DQOpsCheckType.INVALID_USA_PHONE_FORMAT_FOUND: INVALID_USA_PHONE_FORMAT_FOUND_CHECK,
    DQOpsCheckType.INVALID_USA_PHONE_FORMAT_PERCENT: INVALID_USA_PHONE_FORMAT_PERCENT_CHECK,
    DQOpsCheckType.INVALID_USA_ZIPCODE_FORMAT_FOUND: INVALID_USA_ZIPCODE_FORMAT_FOUND_CHECK,
    DQOpsCheckType.INVALID_USA_ZIPCODE_FORMAT_PERCENT: INVALID_USA_ZIPCODE_FORMAT_PERCENT_CHECK,
    # Referential Integrity
    DQOpsCheckType.FOREIGN_KEY_NOT_FOUND: FOREIGN_KEY_NOT_FOUND_CHECK,
    DQOpsCheckType.FOREIGN_KEY_FOUND_PERCENT: FOREIGN_KEY_FOUND_PERCENT_CHECK,
    # Table-level Uniqueness
    DQOpsCheckType.DUPLICATE_RECORD_COUNT: DUPLICATE_RECORD_COUNT_CHECK,
    DQOpsCheckType.DUPLICATE_RECORD_PERCENT: DUPLICATE_RECORD_PERCENT_CHECK,
    # Phase 1: Whitespace & Text
    DQOpsCheckType.EMPTY_TEXT_PERCENT: EMPTY_TEXT_PERCENT_CHECK,
    DQOpsCheckType.WHITESPACE_TEXT_PERCENT: WHITESPACE_TEXT_PERCENT_CHECK,
    DQOpsCheckType.NULL_PLACEHOLDER_TEXT_FOUND: NULL_PLACEHOLDER_TEXT_FOUND_CHECK,
    DQOpsCheckType.NULL_PLACEHOLDER_TEXT_PERCENT: NULL_PLACEHOLDER_TEXT_PERCENT_CHECK,
    DQOpsCheckType.TEXT_SURROUNDED_BY_WHITESPACE_FOUND: TEXT_SURROUNDED_BY_WHITESPACE_FOUND_CHECK,
    DQOpsCheckType.TEXT_SURROUNDED_BY_WHITESPACE_PERCENT: TEXT_SURROUNDED_BY_WHITESPACE_PERCENT_CHECK,
    DQOpsCheckType.TEXTS_NOT_MATCHING_REGEX_PERCENT: TEXTS_NOT_MATCHING_REGEX_PERCENT_CHECK,
    DQOpsCheckType.TEXT_MATCHING_REGEX_PERCENT: TEXT_MATCHING_REGEX_PERCENT_CHECK,
    DQOpsCheckType.MIN_WORD_COUNT: MIN_WORD_COUNT_CHECK,
    DQOpsCheckType.MAX_WORD_COUNT: MAX_WORD_COUNT_CHECK,
    # Phase 2: Geographic
    DQOpsCheckType.VALID_LATITUDE_PERCENT: VALID_LATITUDE_PERCENT_CHECK,
    DQOpsCheckType.VALID_LONGITUDE_PERCENT: VALID_LONGITUDE_PERCENT_CHECK,
    # Phase 2: Numeric
    DQOpsCheckType.NUMBER_BELOW_MIN_VALUE: NUMBER_BELOW_MIN_VALUE_CHECK,
    DQOpsCheckType.NUMBER_ABOVE_MAX_VALUE: NUMBER_ABOVE_MAX_VALUE_CHECK,
    DQOpsCheckType.NUMBER_BELOW_MIN_VALUE_PERCENT: NUMBER_BELOW_MIN_VALUE_PERCENT_CHECK,
    DQOpsCheckType.NUMBER_ABOVE_MAX_VALUE_PERCENT: NUMBER_ABOVE_MAX_VALUE_PERCENT_CHECK,
    DQOpsCheckType.NUMBER_IN_RANGE_PERCENT: NUMBER_IN_RANGE_PERCENT_CHECK,
    DQOpsCheckType.NEGATIVE_VALUES: NEGATIVE_VALUES_CHECK,
    DQOpsCheckType.NEGATIVE_VALUES_PERCENT: NEGATIVE_VALUES_PERCENT_CHECK,
    DQOpsCheckType.NON_NEGATIVE_VALUES: NON_NEGATIVE_VALUES_CHECK,
    DQOpsCheckType.NON_NEGATIVE_VALUES_PERCENT: NON_NEGATIVE_VALUES_PERCENT_CHECK,
    DQOpsCheckType.INTEGER_IN_RANGE_PERCENT: INTEGER_IN_RANGE_PERCENT_CHECK,
    # Phase 3: Statistical
    DQOpsCheckType.SAMPLE_STDDEV_IN_RANGE: SAMPLE_STDDEV_IN_RANGE_CHECK,
    DQOpsCheckType.POPULATION_STDDEV_IN_RANGE: POPULATION_STDDEV_IN_RANGE_CHECK,
    DQOpsCheckType.SAMPLE_VARIANCE_IN_RANGE: SAMPLE_VARIANCE_IN_RANGE_CHECK,
    DQOpsCheckType.POPULATION_VARIANCE_IN_RANGE: POPULATION_VARIANCE_IN_RANGE_CHECK,
    DQOpsCheckType.PERCENTILE_IN_RANGE: PERCENTILE_IN_RANGE_CHECK,
    DQOpsCheckType.PERCENTILE_10_IN_RANGE: PERCENTILE_10_IN_RANGE_CHECK,
    DQOpsCheckType.PERCENTILE_25_IN_RANGE: PERCENTILE_25_IN_RANGE_CHECK,
    DQOpsCheckType.PERCENTILE_75_IN_RANGE: PERCENTILE_75_IN_RANGE_CHECK,
    DQOpsCheckType.PERCENTILE_90_IN_RANGE: PERCENTILE_90_IN_RANGE_CHECK,
    # Phase 4: Accepted Values
    DQOpsCheckType.TEXT_FOUND_IN_SET_PERCENT: TEXT_FOUND_IN_SET_PERCENT_CHECK,
    DQOpsCheckType.NUMBER_FOUND_IN_SET_PERCENT: NUMBER_FOUND_IN_SET_PERCENT_CHECK,
    DQOpsCheckType.EXPECTED_TEXT_VALUES_IN_USE_COUNT: EXPECTED_TEXT_VALUES_IN_USE_COUNT_CHECK,
    DQOpsCheckType.EXPECTED_NUMBERS_IN_USE_COUNT: EXPECTED_NUMBERS_IN_USE_COUNT_CHECK,
    DQOpsCheckType.EXPECTED_TEXTS_IN_TOP_VALUES_COUNT: EXPECTED_TEXTS_IN_TOP_VALUES_COUNT_CHECK,
    DQOpsCheckType.TEXT_VALID_COUNTRY_CODE_PERCENT: TEXT_VALID_COUNTRY_CODE_PERCENT_CHECK,
    DQOpsCheckType.TEXT_VALID_CURRENCY_CODE_PERCENT: TEXT_VALID_CURRENCY_CODE_PERCENT_CHECK,
    # Phase 5: Date Pattern & Data Type
    DQOpsCheckType.TEXT_NOT_MATCHING_DATE_PATTERN_FOUND: TEXT_NOT_MATCHING_DATE_PATTERN_FOUND_CHECK,
    DQOpsCheckType.TEXT_NOT_MATCHING_DATE_PATTERN_PERCENT: TEXT_NOT_MATCHING_DATE_PATTERN_PERCENT_CHECK,
    DQOpsCheckType.TEXT_MATCH_DATE_FORMAT_PERCENT: TEXT_MATCH_DATE_FORMAT_PERCENT_CHECK,
    DQOpsCheckType.TEXT_NOT_MATCHING_NAME_PATTERN_PERCENT: TEXT_NOT_MATCHING_NAME_PATTERN_PERCENT_CHECK,
    DQOpsCheckType.TEXT_PARSABLE_TO_BOOLEAN_PERCENT: TEXT_PARSABLE_TO_BOOLEAN_PERCENT_CHECK,
    DQOpsCheckType.TEXT_PARSABLE_TO_INTEGER_PERCENT: TEXT_PARSABLE_TO_INTEGER_PERCENT_CHECK,
    DQOpsCheckType.TEXT_PARSABLE_TO_FLOAT_PERCENT: TEXT_PARSABLE_TO_FLOAT_PERCENT_CHECK,
    DQOpsCheckType.TEXT_PARSABLE_TO_DATE_PERCENT: TEXT_PARSABLE_TO_DATE_PERCENT_CHECK,
    DQOpsCheckType.DETECTED_DATATYPE_IN_TEXT: DETECTED_DATATYPE_IN_TEXT_CHECK,
    DQOpsCheckType.DETECTED_DATATYPE_IN_TEXT_CHANGED: DETECTED_DATATYPE_IN_TEXT_CHANGED_CHECK,
    # Phase 6: PII Detection
    DQOpsCheckType.CONTAINS_USA_PHONE_PERCENT: CONTAINS_USA_PHONE_PERCENT_CHECK,
    DQOpsCheckType.CONTAINS_EMAIL_PERCENT: CONTAINS_EMAIL_PERCENT_CHECK,
    DQOpsCheckType.CONTAINS_USA_ZIPCODE_PERCENT: CONTAINS_USA_ZIPCODE_PERCENT_CHECK,
    DQOpsCheckType.CONTAINS_IP4_PERCENT: CONTAINS_IP4_PERCENT_CHECK,
    DQOpsCheckType.CONTAINS_IP6_PERCENT: CONTAINS_IP6_PERCENT_CHECK,
    # Phase 7: Change Detection
    DQOpsCheckType.NULLS_PERCENT_CHANGE_1_DAY: NULLS_PERCENT_CHANGE_1_DAY_CHECK,
    DQOpsCheckType.NULLS_PERCENT_CHANGE_7_DAYS: NULLS_PERCENT_CHANGE_7_DAYS_CHECK,
    DQOpsCheckType.NULLS_PERCENT_CHANGE_30_DAYS: NULLS_PERCENT_CHANGE_30_DAYS_CHECK,
    DQOpsCheckType.DISTINCT_COUNT_CHANGE_1_DAY: DISTINCT_COUNT_CHANGE_1_DAY_CHECK,
    DQOpsCheckType.DISTINCT_COUNT_CHANGE_7_DAYS: DISTINCT_COUNT_CHANGE_7_DAYS_CHECK,
    DQOpsCheckType.DISTINCT_COUNT_CHANGE_30_DAYS: DISTINCT_COUNT_CHANGE_30_DAYS_CHECK,
    DQOpsCheckType.DISTINCT_PERCENT_CHANGE_1_DAY: DISTINCT_PERCENT_CHANGE_1_DAY_CHECK,
    DQOpsCheckType.DISTINCT_PERCENT_CHANGE_7_DAYS: DISTINCT_PERCENT_CHANGE_7_DAYS_CHECK,
    DQOpsCheckType.DISTINCT_PERCENT_CHANGE_30_DAYS: DISTINCT_PERCENT_CHANGE_30_DAYS_CHECK,
    DQOpsCheckType.MEAN_CHANGE_1_DAY: MEAN_CHANGE_1_DAY_CHECK,
    DQOpsCheckType.MEAN_CHANGE_7_DAYS: MEAN_CHANGE_7_DAYS_CHECK,
    DQOpsCheckType.MEAN_CHANGE_30_DAYS: MEAN_CHANGE_30_DAYS_CHECK,
    DQOpsCheckType.MEDIAN_CHANGE_1_DAY: MEDIAN_CHANGE_1_DAY_CHECK,
    DQOpsCheckType.MEDIAN_CHANGE_7_DAYS: MEDIAN_CHANGE_7_DAYS_CHECK,
    DQOpsCheckType.MEDIAN_CHANGE_30_DAYS: MEDIAN_CHANGE_30_DAYS_CHECK,
    DQOpsCheckType.SUM_CHANGE_1_DAY: SUM_CHANGE_1_DAY_CHECK,
    DQOpsCheckType.SUM_CHANGE_7_DAYS: SUM_CHANGE_7_DAYS_CHECK,
    DQOpsCheckType.SUM_CHANGE_30_DAYS: SUM_CHANGE_30_DAYS_CHECK,
    # Phase 8: Cross-Table
    DQOpsCheckType.TOTAL_ROW_COUNT_MATCH_PERCENT: TOTAL_ROW_COUNT_MATCH_PERCENT_CHECK,
    DQOpsCheckType.TOTAL_SUM_MATCH_PERCENT: TOTAL_SUM_MATCH_PERCENT_CHECK,
    DQOpsCheckType.TOTAL_MIN_MATCH_PERCENT: TOTAL_MIN_MATCH_PERCENT_CHECK,
    DQOpsCheckType.TOTAL_MAX_MATCH_PERCENT: TOTAL_MAX_MATCH_PERCENT_CHECK,
    DQOpsCheckType.TOTAL_AVERAGE_MATCH_PERCENT: TOTAL_AVERAGE_MATCH_PERCENT_CHECK,
    DQOpsCheckType.TOTAL_NOT_NULL_COUNT_MATCH_PERCENT: TOTAL_NOT_NULL_COUNT_MATCH_PERCENT_CHECK,
    # Phase 9: Table-Level Misc
    DQOpsCheckType.TABLE_AVAILABILITY: TABLE_AVAILABILITY_CHECK,
    DQOpsCheckType.DATA_INGESTION_DELAY: DATA_INGESTION_DELAY_CHECK,
    DQOpsCheckType.RELOAD_LAG: RELOAD_LAG_CHECK,
    DQOpsCheckType.SQL_CONDITION_PASSED_PERCENT_ON_TABLE: SQL_CONDITION_PASSED_PERCENT_ON_TABLE_CHECK,
    DQOpsCheckType.COLUMN_TYPE_CHANGED: COLUMN_TYPE_CHANGED_CHECK,
    # Custom SQL
    DQOpsCheckType.SQL_CONDITION_FAILED_ON_TABLE: SQL_CONDITION_FAILED_ON_TABLE_CHECK,
    DQOpsCheckType.SQL_AGGREGATE_EXPRESSION_ON_TABLE: SQL_AGGREGATE_EXPRESSION_ON_TABLE_CHECK,
    # Phase 10: Text Length Percent
    DQOpsCheckType.TEXT_LENGTH_BELOW_MIN_LENGTH_PERCENT: TEXT_LENGTH_BELOW_MIN_LENGTH_PERCENT_CHECK,
    DQOpsCheckType.TEXT_LENGTH_ABOVE_MAX_LENGTH_PERCENT: TEXT_LENGTH_ABOVE_MAX_LENGTH_PERCENT_CHECK,
    # Phase 10: Column-level Custom SQL
    DQOpsCheckType.SQL_CONDITION_FAILED_ON_COLUMN: SQL_CONDITION_FAILED_ON_COLUMN_CHECK,
    DQOpsCheckType.SQL_CONDITION_PASSED_PERCENT_ON_COLUMN: SQL_CONDITION_PASSED_PERCENT_ON_COLUMN_CHECK,
    DQOpsCheckType.SQL_AGGREGATE_EXPRESSION_ON_COLUMN: SQL_AGGREGATE_EXPRESSION_ON_COLUMN_CHECK,
    DQOpsCheckType.SQL_INVALID_VALUE_COUNT_ON_COLUMN: SQL_INVALID_VALUE_COUNT_ON_COLUMN_CHECK,
    DQOpsCheckType.IMPORT_CUSTOM_RESULT_ON_COLUMN: IMPORT_CUSTOM_RESULT_ON_COLUMN_CHECK,
    # Phase 10: Table-level Custom SQL
    DQOpsCheckType.SQL_INVALID_RECORD_COUNT_ON_TABLE: SQL_INVALID_RECORD_COUNT_ON_TABLE_CHECK,
    # Phase 10: Schema Detection
    DQOpsCheckType.COLUMN_LIST_CHANGED: COLUMN_LIST_CHANGED_CHECK,
    DQOpsCheckType.COLUMN_LIST_OR_ORDER_CHANGED: COLUMN_LIST_OR_ORDER_CHANGED_CHECK,
    DQOpsCheckType.COLUMN_TYPES_CHANGED: COLUMN_TYPES_CHANGED_CHECK,
    # Phase 11: Import External Results
    DQOpsCheckType.IMPORT_CUSTOM_RESULT_ON_TABLE: IMPORT_CUSTOM_RESULT_ON_TABLE_CHECK,
    # Phase 11: Generic Change Detection
    DQOpsCheckType.ROW_COUNT_CHANGE: ROW_COUNT_CHANGE_CHECK,
    DQOpsCheckType.NULLS_PERCENT_CHANGE: NULLS_PERCENT_CHANGE_CHECK,
    DQOpsCheckType.DISTINCT_COUNT_CHANGE: DISTINCT_COUNT_CHANGE_CHECK,
    DQOpsCheckType.DISTINCT_PERCENT_CHANGE: DISTINCT_PERCENT_CHANGE_CHECK,
    DQOpsCheckType.MEAN_CHANGE: MEAN_CHANGE_CHECK,
    DQOpsCheckType.MEDIAN_CHANGE: MEDIAN_CHANGE_CHECK,
    DQOpsCheckType.SUM_CHANGE: SUM_CHANGE_CHECK,
    # Phase 12: Anomaly Detection
    DQOpsCheckType.ROW_COUNT_ANOMALY: ROW_COUNT_ANOMALY_CHECK,
    DQOpsCheckType.DATA_FRESHNESS_ANOMALY: DATA_FRESHNESS_ANOMALY_CHECK,
    DQOpsCheckType.NULLS_PERCENT_ANOMALY: NULLS_PERCENT_ANOMALY_CHECK,
    DQOpsCheckType.DISTINCT_COUNT_ANOMALY: DISTINCT_COUNT_ANOMALY_CHECK,
    DQOpsCheckType.DISTINCT_PERCENT_ANOMALY: DISTINCT_PERCENT_ANOMALY_CHECK,
    DQOpsCheckType.SUM_ANOMALY: SUM_ANOMALY_CHECK,
    DQOpsCheckType.MEAN_ANOMALY: MEAN_ANOMALY_CHECK,
    DQOpsCheckType.MEDIAN_ANOMALY: MEDIAN_ANOMALY_CHECK,
    DQOpsCheckType.MIN_ANOMALY: MIN_ANOMALY_CHECK,
    DQOpsCheckType.MAX_ANOMALY: MAX_ANOMALY_CHECK,
    # Phase 12: Cross-Source Comparison
    DQOpsCheckType.ROW_COUNT_MATCH: ROW_COUNT_MATCH_CHECK,
    DQOpsCheckType.COLUMN_COUNT_MATCH: COLUMN_COUNT_MATCH_CHECK,
    DQOpsCheckType.SUM_MATCH: SUM_MATCH_CHECK,
    DQOpsCheckType.MIN_MATCH: MIN_MATCH_CHECK,
    DQOpsCheckType.MAX_MATCH: MAX_MATCH_CHECK,
    DQOpsCheckType.MEAN_MATCH: MEAN_MATCH_CHECK,
    DQOpsCheckType.NOT_NULL_COUNT_MATCH: NOT_NULL_COUNT_MATCH_CHECK,
    DQOpsCheckType.NULL_COUNT_MATCH: NULL_COUNT_MATCH_CHECK,
    DQOpsCheckType.DISTINCT_COUNT_MATCH: DISTINCT_COUNT_MATCH_CHECK,
}


def get_check(check_type: DQOpsCheckType) -> DQOpsCheck:
    """Get a check definition by type.

    Args:
        check_type: The type of check to retrieve.

    Returns:
        The check definition.

    Raises:
        ValueError: If check type is not registered.
    """
    if check_type not in CHECK_REGISTRY:
        raise ValueError(f"Unknown check type: {check_type}")
    return CHECK_REGISTRY[check_type]


def list_checks() -> list[DQOpsCheck]:
    """List all registered checks.

    Returns:
        List of all checks.
    """
    return list(CHECK_REGISTRY.values())


def get_column_level_checks() -> list[DQOpsCheck]:
    """Get all column-level checks.

    Returns:
        List of column-level checks.
    """
    return [c for c in CHECK_REGISTRY.values() if c.is_column_level]


def get_table_level_checks() -> list[DQOpsCheck]:
    """Get all table-level checks.

    Returns:
        List of table-level checks.
    """
    return [c for c in CHECK_REGISTRY.values() if not c.is_column_level]


def get_checks_by_category(category: str) -> list[DQOpsCheck]:
    """Get all checks in a category.

    Args:
        category: The category to filter by (e.g., "volume", "nulls").

    Returns:
        List of checks in the category.
    """
    return [c for c in CHECK_REGISTRY.values() if c.category == category]
